# integration tests for svelte ecosystem projects - scheduled or manual run for all suites
name: svelte-ecosystem-ci

env:
  # 7 GiB by default on GitHub, setting to 6 GiB
  # https://docs.github.com/en/actions/using-github-hosted-runners/about-github-hosted-runners#supported-runners-and-hardware-resources
  NODE_OPTIONS: --max-old-space-size=6144
  # configure corepack to be strict but not download newer versions or change anything
  COREPACK_DEFAULT_TO_LATEST: 0
  COREPACK_ENABLE_AUTO_PIN: 0
  COREPACK_ENABLE_STRICT: 1
  # see https://turbo.build/repo/docs/telemetry#how-do-i-opt-out
  TURBO_TELEMETRY_DISABLED: 1
  DO_NOT_TRACK: 1
on:
  schedule:
    - cron: "0 5 * * 1,3,5" # monday,wednesday,friday 5AM
  workflow_dispatch:
    inputs:
      refType:
        description: "type of ref"
        required: true
        type: choice
        options:
          - branch
          - tag
          - commit
          - release
        default: "branch"
      ref:
        description: "svelte ref to use"
        required: true
        type: string
        default: "main"
      repo:
        description: "svelte repository to use"
        required: true
        type: string
        default: "sveltejs/svelte"
      sendDiscordReport:
        description: "send results to discord"
        type: boolean
  repository_dispatch:
    types: [ecosystem-ci]
jobs:
  test-ecosystem:
    timeout-minutes: 30
    runs-on: ubuntu-latest
    strategy:
      matrix:
        suite:
          - eslint-plugin-svelte
          - language-tools
          - mdsvex
          - melt-ui
          - melt-ui-preprocessor
          - prettier-plugin-svelte
          - rollup-plugin-svelte
          - skeleton
          - sv
          - svelte-eslint-parser
          - svelte-loader
          - svelte-preprocess
          - sveltekit
          - vite-plugin-svelte
      fail-fast: false
    permissions:
      contents: read # to clone the repo
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: ^22.14.0
        id: setup-node
      - run: corepack enable
      - run: pnpm --version
      - run: pnpm i --frozen-lockfile
      - run: >-
          pnpm tsx ecosystem-ci.ts
          --${{ inputs.refType || github.event.client_payload.refType || 'branch' }} ${{ inputs.ref || github.event.client_payload.ref || 'main' }}
          --repo ${{ inputs.repo || github.event.client_payload.repo || 'sveltejs/svelte' }}
          ${{ matrix.suite }}
        id: ecosystem-ci-run
      - if: always() && (inputs.sendDiscordReport || github.event_name != 'workflow_dispatch')
        run: pnpm tsx discord-webhook.ts
        env:
          WORKFLOW_NAME: ci
          REF_TYPE: ${{ inputs.refType || github.event.client_payload.refType || 'branch' }}
          REF: ${{ inputs.ref || github.event.client_payload.ref || 'main' }}
          REPO: ${{ inputs.repo || github.event.client_payload.repo || 'sveltejs/svelte' }}
          SUITE: ${{ matrix.suite }}
          STATUS: ${{ job.status }}
          DISCORD_WEBHOOK_URL: ${{ secrets.DISCORD_WEBHOOK_URL }}
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
